# Generated by Django 5.2.7 on 2025-11-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('van', 'Van'), ('truck', 'Truck')], max_length=10)),
                ('max_capacity_kg', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cost_per_km', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('current_x', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('current_y', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='logistics.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('pickup_x', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('pickup_y', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('delivery_x', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('delivery_y', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='logistics.vehicle')),
            ],
        ),
    ]
